server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always
spring:
  application:
    name: orders-service
  datasource:
    url: jdbc:mysql://localhost:3306/orders_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: appuser
    password: appsecret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
