server:
  port: 8081
spring:
  application:
    name: products-service
  datasource:
    url: jdbc:mysql://localhost:3306/products_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: appuser
    password: appsecret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: health,info
